### ISSUE TITLE
FinTS::DialogError with ING-DiBa

### ISSUE THREAD

**Issue by kiliankoe** [playtestcloud/ruby_fints#8]
Hi! 

This is basically the same issue as https://github.com/schurig/ynab-bank-importer/issues/64. 

```ruby
require 'ruby_fints'
FinTS::Client.logger.level = Logger::DEBUG
f = FinTS::PinTanClient.new('50010517', 'my_username', 'my_password', 'https://fints.ing.de/fints/')
f.get_sepa_accounts
```

Gives me the following output with a `FinTS::DialogError` 😕  

```
I, [2019-04-25T07:48:39.917712 #29]  INFO -- FinTS::Client: Initialize SYNC
D, [2019-04-25T07:48:39.918193 #29] DEBUG -- FinTS::Client: Sending SYNC: HNHBK:1:3+000000000379+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20190425:074839+2:2:13:@8@00000000:5:1+280:50010517:REDACTED:S:0:0+0'HNVSD:999:1+@216@HNSHK:2:4+PIN:1+999+6820269+1+1+1::0+1+1:20190425:074839+1:999:1+6:10:16+280:50010517:REDACTED:S:0:0'HKIDN:3:2+280:50010517+REDACTED+0+1'HKVVB:4:3+0+0+1+ruby_fints+0.0.4'HKSYN:5:3+0'HNSHA:6:2+6820269++REDACTED''HNHBS:7:1+1'
I, [2019-04-25T07:48:39.918269 #29]  INFO -- FinTS::Client: Sending Message
D, [2019-04-25T07:48:39.918622 #29] DEBUG -- FinTS::Client: << HNHBK:1:3+000000000379+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20190425:074839+2:2:13:@8@00000000:5:1+280:50010517:REDACTED:S:0:0+0'HNVSD:999:1+@216@HNSHK:2:4+PIN:1+999+6820269+1+1+1::0+1+1:20190425:074839+1:999:1+6:10:16+280:50010517:REDACTED:S:0:0'HKIDN:3:2+280:50010517+REDACTED+0+1'HKVVB:4:3+0+0+1+ruby_fints+0.0.4'HKSYN:5:3+0'HNSHA:6:2+6820269++REDACTED''HNHBS:7:1+1'
D, [2019-04-25T07:48:42.141609 #29] DEBUG -- FinTS::Client: >> HNHBK:1:3+000000000211+300+000006IJEV7V3RF87QRBNDEIIB2UV4+1+000006IJEV7V3RF87QRBNDEIIB2UV4:1'HIRMG:2:2:+9800::Der Dialog wurde abgebrochen.+9010::Ungültiger Signaturaufbau?: Fehler im Segmentaufbau.'HNHBS:3:1+1'
Traceback (most recent call last):
        7: from /usr/local/bin/irb:23:in `<main>'
        6: from /usr/local/bin/irb:23:in `load'
        5: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):5
        3: from /usr/local/bundle/gems/ruby_fints-0.0.4/lib/fints/client.rb:19:in `get_sepa_accounts'
        2: from /usr/local/bundle/gems/ruby_fints-0.0.4/lib/fints/dialog.rb:39:in `sync'
        1: from /usr/local/bundle/gems/ruby_fints-0.0.4/lib/fints/dialog.rb:83:in `send_msg'
FinTS::DialogError ({"9800"=>"Der Dialog wurde abgebrochen.", "9010"=>"Ung\u00FCltiger Signaturaufbau?: Fehler im Segmentaufbau."})
```

Apparently this is working fine for others. Is there anything I can do to further debug this issue? I can successfully authenticate to my account via MoneyMoney using the same credentials.

Thanks for any help in advance!

**Comment by gingerlime** [comment]
I tested with my ING-DiBa account and it's working for me... Sorry that it's not really of much help. I'm having a similar problem with Targobank (see #7), but only for some operations. I have a feeling banks aren't implementing things consistently, but really no clue about the whole FinTS shenanigans...
